sudo: required
services:
  - docker

before_install:
  - docker build -t shchepinsky/react-test -f ./client/Dockerfile.dev ./client

script:
  # -- --coverage prevents watch mode of jest an it will exit
  - docker run -e CI=true shchepinsky/react-test npm test -- --coverage

after_success:
  - docker build -t shchepinsky/multi-client ./client
  - docker build -t shchepinsky/multi-nginx ./nginx
  - docker build -t shchepinsky/multi-server ./server
  - docker build -t shchepinsky/multi-worker ./worker
  # log into docker CLI
  # pipe emits output of echo to the stdin of docker command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push shchepinsky/multi-client
  - docker push shchepinsky/multi-nginx
  - docker push shchepinsky/multi-server
  - docker push shchepinsky/multi-worker